# Generated by Django 3.1.9 on 2021-06-29 08:41

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0002_auto_20210629_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=django_quill.fields.QuillField(),
        ),
    ]
