# Generated by Django 3.1.9 on 2021-06-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='comment',
        ),
    ]
