# Generated by Django 3.1.9 on 2021-06-29 07:48

import django.core.validators
from django.db import migrations, models
import profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_remove_profile_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='discount_percent',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), profile.models.discount_model_validator]),
        ),
    ]
