# Generated by Django 3.1.9 on 2021-06-02 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
