# Generated by Django 3.1.9 on 2021-06-29 13:39

from django.db import migrations, models
import shop.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('shop', '0003_auto_20210629_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, upload_to=shop.models.brand_directory_path),
        ),
        migrations.AddField(
            model_name='category',
            name='background_image',
            field=models.ImageField(default='C:\\CODES\\Python\\Django\\Electroshop\\electroshop\\shop\\static\\images\\mainboard.jpg', upload_to=shop.models.category_directory_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
