# Generated by Django 3.1.9 on 2021-06-29 18:26

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210629_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='background_image',
            field=models.ImageField(default='C:\\CODES\\PYTHON\\Django\\electroshop\\electroshop\\shop\\static\\images\\mainboard.jpg', upload_to=shop.models.category_directory_path),
        ),
    ]
