# Generated by Django 3.1.9 on 2021-06-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210629_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_persian',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
