# Generated by Django 3.1.9 on 2021-07-11 19:51

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210630_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='background_image',
            field=models.ImageField(default='category_default.jpg', upload_to=shop.models.category_directory_path),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_camera', models.CharField(max_length=20)),
                ('lcd', models.CharField(max_length=20)),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera', to='shop.product')),
            ],
        ),
    ]
