# Generated by Django 3.1.9 on 2021-07-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210712_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='end_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
