# Generated by Django 3.1.9 on 2021-06-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=dict)),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('total_number', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ManyToManyField(blank=True, related_name='product_cart', to='shop.Product')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_cart', to='profile.profile')),
            ],
        ),
    ]
