# Generated by Django 3.1.9 on 2021-06-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210613_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_number',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
