# Generated by Django 3.1.9 on 2021-06-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20210613_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
