# Generated by Django 3.1.9 on 2021-06-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cart_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price_after_discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
