# Generated by Django 3.1.9 on 2021-07-14 17:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20210629_1218'),
        ('shop', '0008_auto_20210712_0021'),
        ('cart', '0010_cart_price_after_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('value', models.PositiveIntegerField(default=0)),
                ('percent', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0), profile.models.discount_model_validator])),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='shop.product')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_discount_code', to='profile.profile')),
            ],
        ),
    ]
